### ISSUE TITLE
Processor should create annotation.yml file and required path

### ISSUE THREAD

**Issue by lfvbarcus** [Luftfartsverket/reqstool-python-decorators#11]
Using GitHub Actions, a specific step is required to make the dist folder before hatch build is run. The decorator processor should do this  if the path does not exist.  

example code to implement in order to achieve this:

```
def create_path_and_file(directory: str):
    # Check if the directory exists
    if not os.path.exists(directory):
        # If not, create the directory
        os.makedirs(directory)
        print(f"Directory '{directory}' created.")
```

Also, the documentation should be updated as the import examples are incorrect. 

Also update name of ProcessDecorator -> DecoratorProcessor

**Comment by lfvdavid** [comment]
Fixed in #12
